config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  devise_for :admins, path: 'admin', controllers: { sessions: "admins/sessions", registrations: 'admins/registrations' }
  devise_for :users, path: 'user', controllers: { sessions: "users/sessions", registrations: 'users/registrations' }
  resources :tasks do
    member do
      get :start_working
      get :back_to_do
      get :send_to_review
      get :close
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  belongs_to :admin, foreign_key: :created_by
  belongs_to :user, foreign_key: :assignee
  validates :subject, :description, :status, :type, :assignee, presence: true

  enum status: {
    to_do: 'To Do',
    in_progress: 'In Progress',
    in_review: 'In Review',
    done: 'Done'
  }

  def self.types
    %w[Issue Story]
  end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  before_action :set_task, except: %i[index new create]
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
    authorize @tasks
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show; end

  # GET /tasks/new
  def new
    @task = Task.new
    authorize @task
  end

  # GET /tasks/1/edit
  def edit
    @task = to_task
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.created_by = current_admin.id

    respond_to do |format|
      if @task.save
        TaskMailer.with(task: @task).created_task_email.deliver_now
        html_response(format, to_task, 'Task was successfully created.')
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    @task = to_task
    respond_to do |format|
      if @task.update(task_params)
        html_response(format, @task, 'Task was successfully updated.')
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      html_response(format, tasks_url, 'Task was successfully destroyed.')
    end
  end

  def start_working
    @task.status = 'In Progress'
    @task.save
    TaskMailer.with(task: @task).in_process_status_email.deliver_now

    redirect_to task_url(@task)
  end

  def back_to_do
    @task.status = 'To Do'
    @task.save

    redirect_to task_url(@task)
  end

  def send_to_review
    @task.status = 'In Review'
    @task.save
    TaskMailer.with(task: @task).in_review_status_email.deliver_now

    redirect_to task_url(@task)
  end

  def close
    @task.status = 'Done'
    @task.save
    TaskMailer.with(task: @task).done_status_email.deliver_now

    redirect_to task_url(@task)
  end

  private

  def set_task
    @task = Task.find(params[:id])
    authorize @task
  end

  def task_params
    params.require(:task).permit(
      :subject, :description,
      :type, :status, :assignee
    )
  end

  def to_task
    @task.becomes(Task)
  end

  def html_response(format, url, message)
    format.html { redirect_to url, notice: message }
  end

  def record_not_found
    flash[:danger] = 'Task not found'
    redirect_to tasks_url
  end
end

app/helpers/tasks_helper.rb
# frozen_string_literal: true

module TasksHelper
  def task_in_to_do?
    @task.status == 'to_do'
  end

  def task_in_process?
    @task.status == 'in_progress'
  end

  def task_in_review?
    @task.status == 'in_review' && admin_signed_in?
  end
end

app/views/tasks/_form.html.erb
<div class="task-form">
  <%= simple_form_for task do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :subject, label: 'Subject' %>
      <%= f.input :description, as: :text %>
      <%= f.input :status, collection: Task.statuses.values, default: Task.statuses.values.first %>
      <%= f.input :type, as: :radio_buttons, collection: Task.types %>
      <%= f.input :assignee, collection: User.all %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, class: 'btn btn-primary' %>
      <%= link_to 'Back', :back, class: 'btn btn-outline-secondary' %>
    </div>
  <% end %>
</div>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>
<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">Subject</th>
      <th scope="col">Description</th>
      <th scope="col">Type</th>
      <th scope="col">Status</th>
      <th scope="col">Created at</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= link_to task.subject, task.becomes(Task) %></td>
        <td><%= task.description %></td>
        <td><%= task.type %></td>
        <td><%= Task.statuses[task.status] %></td>
        <td><%= task.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<div class="task row">
  <div class="col md 9">
    <div class="type">
      <p><%= @task.type %></p>
    </div>
    <div class="subject">
      <h1><%= @task.subject %></h1>
    </div>
    <div class="description">
      <p><%= @task.description %></p>
    </div>
  </div>

  <% if task_in_to_do? %>
    <p><%= link_to "Start working", start_working_task_path(@task), class: 'btn btn-primary' %><p>
  <% end %>

  <% if task_in_process? %>
    <p><%= link_to "Back to To Do", back_to_do_task_path(@task), class: 'btn btn-info' %><p>
    <p><%= link_to "Send to review", send_to_review_task_path(@task), class: 'btn btn-secondary' %><p>
  <% end %>

  <% if task_in_review? %>
    <p><%= link_to "Close", close_task_path(@task), class: 'btn btn-info' %><p>
  <% end %>

  <div class="col md 3">
    <% if policy(@task).edit? %>
      <p><%= link_to "Edit task", edit_task_path(@task) %></p>
    <% end %>
    <div class="status">
      <p><%= Task.statuses[@task.status] %></p>
    </div>
    <div class="created_at">
      <p>Created: <%= @task.created_at %></p>
    </div>
    <div class="updated_at">
      <p>Updated: <%= @task.updated_at %></p>
    </div>
  </div>
</div>