config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  devise_for :admins, path: 'admin', controllers: { sessions: "admins/sessions", registrations: 'admins/registrations' }
  devise_for :users, path: 'user', controllers: { sessions: "users/sessions", registrations: 'users/registrations' }
  resources :tasks do
    member do
      get :start_working
      get :back_to_do
      get :send_to_review
      get :close
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    render layout: false
  end
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TasksList</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body id="home">
  <%= render "layouts/alert" %>
  
  <div class="homepage">
    <div class="container h-100">
      <div class="row h-100 align-items-center justify-content-center text-center">
        <div class="col-lg-10 align-self-end">
          <h1 class="text-uppercase text-white font-weight-bold">Welcome to Task List</h1>
          <hr class="divider my-4">
        </div>
        <div class="col-lg-8 align-self-baseline">
          <p class="text-white-75 font-weight-light mb-5">Start Task list can help you to manage your tasks! Just download a theme and start customizing, no strings attached!</p>
          <%= link_to 'For users', user_session_path, class: 'btn-xl' %>
          <%= link_to 'For admins', admin_session_path, class: 'btn-xl' %>
        </div>
      </div>
    </div>
  </div>
</body>
</html>