config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  devise_for :admins, path: 'admin', controllers: { sessions: "admins/sessions", registrations: 'admins/registrations' }
  devise_for :users, path: 'user', controllers: { sessions: "users/sessions", registrations: 'users/registrations' }
  resources :tasks do
    member do
      get :start_working
      get :back_to_do
      get :send_to_review
      get :close
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_alert.html.erb
<% flash.each do |name,message| %>
  <div class="alert <%= bootstrap_class_for(name) %>">
    <button class="close" data-dismiss="alert">&times;</button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="container sticky-top">
  <nav class="navbar navbar-expand-lg text-decoration">
    <%= link_to 'Tasks', tasks_path, class: "navbar-brand" %>
     <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <% if admin_signed_in? %>
          <%= link_to "New Task", new_task_path, class: "nav-link"  %>
        <% end %>
      </li>
     </ul>
     <ul class="navbar-nav pull-xs-right">
      <% if admin_signed_in? %>
        <li class="nav-item active">
          <%= link_to 'Log out admin', destroy_admin_session_path, method: :delete %>
        </li>
      <% end %>
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to 'Log out user', destroy_user_session_path, method: :delete %>
        </li>
      <% end %>
     </ul>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TasksList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navigation" %>
    
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <%= render "layouts/alert" %>
        </div>
      </div>
    </div>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>